
[General]
	#In what radius should the Single Chunk Loader be able to load chunks?
	#Range: 1 ~ 8
	singleChunkLoaderRadius = 1
	#In what radius should the Basic Chunk Loader be able to load chunks?
	#Range: 1 ~ 8
	basicChunkLoaderRadius = 2
	#In what radius should the Advanced Chunk Loader be able to load chunks?
	#Range: 1 ~ 8
	advancedChunkLoaderRadius = 3
	#In what radius should the Ultimate Chunk Loader be able to load chunks?
	#Range: 1 ~ 8
	ultimateChunkLoaderRadius = 4

