
#Server side blocks configs
[blocks]

	[blocks.turn_table]
		#can rotate entities standing on it?
		rotate_entities = true
		#blocks that can't be rotated. Some special ones like chests, beds and pistons are already hardcoded
		blacklist = ["minecraft:end_portal_frame"]

	#I haven't tested most of the mods included here. let me know if they work
	[blocks.cage]
		#catchable mobs
		cage_mobs = ["minecraft:endermite", "minecraft:slime", "minecraft:parrot", "minecraft:bee", "minecraft:magma_cube", "minecraft:vex", "minecraft:rabbit", "minecraft:cat", "minecraft:chicken", "minecraft:bat", "minecraft:fox", "minecraft:ocelot", "quark:crab", "quark:foxhound", "quark:frog", "autumnity:snail", "buzzierbees:honey_slime", "swampexpansion:slabfish"]
		#allow all mobs to be captured by jars
		cage_allow_all_mobs = false
		#additional mobs that you'll be able to catch with the added condition that it has to be a baby variant. No need to include the ones already in cage_mobs
		cage_baby_mobs = ["minecraft:cow", "minecraft:sheep", "minecraft:pig"]

	[blocks.speaker_block]
		#maximum range
		#Range: 0 ~ 256
		range = 64

	[blocks.sack]
		#additional sack slots divided by 2. Number of slots will be 5 + additional_slots*2
		#Range: 0 ~ 2
		additional_slots = 0
		#penalize the player with slowness effecn when carring too many sacks
		sack_penality = true
		#maximum number of sacks after which the slowness effect will be applied. each multiple of this number will further slow the player down
		#Range: 0 ~ 50
		sack_increment = 2

	[blocks.spring_launcher]
		#fall distance needed to trigger the automatic spring launch
		#Range: 0 ~ 512
		fall_height_required = 5
		#spring launcher launch speed
		#Range: 0.0 ~ 16.0
		velocity = 1.5

	[blocks.bellows]
		#velocity increase uses this equation: 
		#vel = base_vel*((range-entity_distance)/range) with base_vel = base_velocity_scaling/period 
		#note that the block will push further the faster it's pulsing
		#Range: 0.0 ~ 64.0
		base_velocity_scaling = 5.0
		#bellows pushes air following this equation: 
		#air=(sin(2PI*ticks/period)<0), with period = base_period-(redstone_power-1)*power_scaling 
		#represents base period at 1 power
		#Range: 1 ~ 512
		base_period = 78
		#note that it will still only keep alive the two fire blocks closer to it
		#Range: 0 ~ 16
		range = 5
		#entities with velocity greated than this won't be pushed
		#Range: 0.0 ~ 16.0
		power_scaling = 2.0
		#sets velocity changed flag when pushing entities +
		#causes pushing animation to be smooth client side but also restricts player movement when being pushed
		velocity_changed_flag = true

	[blocks.safe]
		#makes safes only breakable by their owner or by a player in creative
		prevent_breaking = false

	[blocks.notice_board]
		#allow notice boards to accept and display any item, not just maps and books
		allow_any_item = false

	[blocks.jar]
		#catchable mobs 
		#due to a vanilla bug some mobs might not render correctly or at all
		mobs = ["minecraft:slime", "minecraft:bee", "minecraft:magma_cube", "swampexpansion:slabfish"]
		#tinted jar catchable mobs
		tinted_jar_mobs = ["minecraft:endermite", "minecraft:slime", "minecraft:bee", "minecraft:magma_cube", "minecraft:vex", "swampexpansion:slabfish"]
		#allow right click to instantly eat or drink food or potions inside a jar.
		#Disable if you think this ability is op. Cookies are excluded
		drink_from_jar = true
		#jar liquid capacity: leave at 12 for pixel accuracy
		#Range: 0 ~ 1024
		capacity = 12

#Configure spawning conditions
[spawns]

	[spawns.firefly]
		#Minimum group size
		#Range: 0 ~ 64
		min = 5
		#Spawnable biomes
		biomes = ["minecraft:swamp", "minecraft:swamp_hills", "minecraft:plains", "minecraft:sunflower_plains", "minecraft:dark_forest", "minecraft:dark_forest_hills", "biomesoplenty:flower_meadow", "biomesoplenty:fir_clearing", "biomesoplenty:grove_lakes", "biomesoplenty:grove", "biomesoplenty:highland_moor", "biomesoplenty:wetland_marsh", "biomesoplenty:deep_bayou"]
		#Maximum group size
		#Range: 0 ~ 64
		max = 9
		#Whitelisted mods. All biomes from said mods will be able to spawn fireflies. Use the one above for more control
		mod_whitelist = []
		#Spawn weight 
		#Set to 0 to disable spawning entirely
		#Range: 0 ~ 100
		weight = 3

#entities parameters
[entities]

	[entities.firefly]
		#firefly animation period
		#note that actual period will be this + a random number between 0 and 10
		#this needs to be here to allow correct despawning of the entity when it's not glowing
		#check client configs come more animation settings
		#Range: 1 ~ 200
		period = 65
		#despawn during the day
		despawn = true
		#firefly flying speed
		#Range: 0.0 ~ 10.0
		speed = 0.3

#Vanilla tweaks
[tweaks]

	[tweaks.wall_lantern]
		#mod ids of mods that have lantern block that extend the base lantern class but don't look like one
		mod_blacklist = ["extlights"]
		#allow wall lanterns placement
		enabled = true

	[tweaks.throwable_bricks]
		#throw bricks at your foes! Might glass blocks
		enabled = true

